<?php

return [
    'defaults' => [
        'service_fee' => 0.35,
        'service_fee_type' => 'percent',
        'network_fee' => 0.05,
        'network_fee_type' => 'percent',
        'status' => 0,
        'driver' => 'local',
        'image' => null,
        'last_rate_sync_error' => 'Pending bootstrap sync after deploy',
    ],
    'currencies' => [
        ['code' => 'BTC', 'name' => 'Bitcoin', 'symbol' => 'BTC', 'is_stablecoin' => false, 'min_send' => 0.0003, 'max_send' => 25],
        ['code' => 'ETH', 'name' => 'Ethereum', 'symbol' => 'ETH', 'is_stablecoin' => false, 'min_send' => 0.005, 'max_send' => 500],
        ['code' => 'ETH_ARB', 'name' => 'Ethereum (Arbitrum)', 'symbol' => 'ETH', 'is_stablecoin' => false, 'min_send' => 0.003, 'max_send' => 500],
        ['code' => 'ETH_BASE', 'name' => 'Ethereum (Base)', 'symbol' => 'ETH', 'is_stablecoin' => false, 'min_send' => 0.003, 'max_send' => 500],
        ['code' => 'ETH_OPT', 'name' => 'Ethereum (Optimism)', 'symbol' => 'ETH', 'is_stablecoin' => false, 'min_send' => 0.003, 'max_send' => 500],
        ['code' => 'BNB', 'name' => 'BNB', 'symbol' => 'BNB', 'is_stablecoin' => false, 'min_send' => 0.01, 'max_send' => 5000],
        ['code' => 'SOL', 'name' => 'Solana', 'symbol' => 'SOL', 'is_stablecoin' => false, 'min_send' => 0.05, 'max_send' => 50000],
        ['code' => 'TRX', 'name' => 'TRON', 'symbol' => 'TRX', 'is_stablecoin' => false, 'min_send' => 20, 'max_send' => 5000000],
        ['code' => 'TON', 'name' => 'Toncoin', 'symbol' => 'TON', 'is_stablecoin' => false, 'min_send' => 0.5, 'max_send' => 500000],
        ['code' => 'LTC', 'name' => 'Litecoin', 'symbol' => 'LTC', 'is_stablecoin' => false, 'min_send' => 0.01, 'max_send' => 10000],
        ['code' => 'ARB_ARB', 'name' => 'Arbitrum', 'symbol' => 'ARB', 'is_stablecoin' => false, 'min_send' => 2, 'max_send' => 1000000],
        ['code' => 'OP_OPT', 'name' => 'Optimism', 'symbol' => 'OP', 'is_stablecoin' => false, 'min_send' => 1, 'max_send' => 1000000],
        ['code' => 'SHIB_ERC20', 'name' => 'Shiba Inu (ERC20)', 'symbol' => 'SHIB', 'is_stablecoin' => false, 'min_send' => 100000, 'max_send' => 100000000000],
        ['code' => 'SHIB_BSC', 'name' => 'Shiba Inu (BSC)', 'symbol' => 'SHIB', 'is_stablecoin' => false, 'min_send' => 100000, 'max_send' => 100000000000],
        ['code' => 'PEPE_ERC20', 'name' => 'Pepe (ERC20)', 'symbol' => 'PEPE', 'is_stablecoin' => false, 'min_send' => 1000000, 'max_send' => 1000000000000],
        ['code' => 'PEPE_BSC', 'name' => 'Pepe (BSC)', 'symbol' => 'PEPE', 'is_stablecoin' => false, 'min_send' => 1000000, 'max_send' => 1000000000000],
        ['code' => 'TRUMP_SOL', 'name' => 'Official Trump (Solana)', 'symbol' => 'TRUMP', 'is_stablecoin' => false, 'min_send' => 0.5, 'max_send' => 100000],
        ['code' => 'XAUT_ERC20', 'name' => 'Tether Gold (ERC20)', 'symbol' => 'XAUT', 'is_stablecoin' => false, 'min_send' => 0.01, 'max_send' => 5000],
        ['code' => 'USDT_TRC20', 'name' => 'Tether USD (TRC20)', 'symbol' => 'USDT', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDT_ERC20', 'name' => 'Tether USD (ERC20)', 'symbol' => 'USDT', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDT_BSC', 'name' => 'Tether USD (BSC)', 'symbol' => 'USDT', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDT_SOL', 'name' => 'Tether USD (Solana)', 'symbol' => 'USDT', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDT_ARB', 'name' => 'Tether USD (Arbitrum)', 'symbol' => 'USDT', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDT_OPT', 'name' => 'Tether USD (Optimism)', 'symbol' => 'USDT', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDT_TON', 'name' => 'Tether USD (TON)', 'symbol' => 'USDT', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDC_ERC20', 'name' => 'USD Coin (ERC20)', 'symbol' => 'USDC', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDC_BSC', 'name' => 'USD Coin (BSC)', 'symbol' => 'USDC', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDC_SOL', 'name' => 'USD Coin (Solana)', 'symbol' => 'USDC', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDC_ARB', 'name' => 'USD Coin (Arbitrum)', 'symbol' => 'USDC', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDC_OPT', 'name' => 'USD Coin (Optimism)', 'symbol' => 'USDC', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDC_BASE', 'name' => 'USD Coin (Base)', 'symbol' => 'USDC', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'DAI_ERC20', 'name' => 'Dai (ERC20)', 'symbol' => 'DAI', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'DAI_BSC', 'name' => 'Dai (BSC)', 'symbol' => 'DAI', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'DAI_ARB', 'name' => 'Dai (Arbitrum)', 'symbol' => 'DAI', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'DAI_OPT', 'name' => 'Dai (Optimism)', 'symbol' => 'DAI', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'DAI_BASE', 'name' => 'Dai (Base)', 'symbol' => 'DAI', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'TUSD_ERC20', 'name' => 'TrueUSD (ERC20)', 'symbol' => 'TUSD', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'TUSD_BSC', 'name' => 'TrueUSD (BSC)', 'symbol' => 'TUSD', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'USDD_TRC20', 'name' => 'USDD (TRC20)', 'symbol' => 'USDD', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'PYUSD_ERC20', 'name' => 'PayPal USD (ERC20)', 'symbol' => 'PYUSD', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
        ['code' => 'PYUSD_SOL', 'name' => 'PayPal USD (Solana)', 'symbol' => 'PYUSD', 'is_stablecoin' => true, 'min_send' => 10, 'max_send' => 1000000],
    ],
];
