<?php
$arr = [
     "Change Password",
     "Experience the ease and security of our streamlined password change process – regain access to your account in just a few clicks!",
     "Enter your current password",
     "Enter new password",
     "Repeat password",
     "Confirm Password!",
     "Please enter your new password again to confirm and ensure accuracy.",
     "Forgot Your Password",
     "Recover Password!",
     "Regain access with your seamless and secure account retrieval process in just a few clicks!",
     "Email address",
     "Send Link",
     "Reset Password!",
     "Initiate the password reset process effortlessly and securely to regain control of your account with just a few simple steps.",
     "New Password",
     "Confirm New Password",
     "Reset Password",
     "Verification here!",
     "Please enter the verification code to authenticate your identity and proceed with the verification process.",
     "2 FA Code",
     "Submit",
     "Email Verification Here!",
     "Ensure account security with a quick and simple email verification process. Stay protected, stay connected.",
     "Code",
     "Resend code",
     "resend",
     "Phone Number Verify Here!",
     "Validate your phone number effortlessly for enhanced account protection. Verification made simple, security assured.",
     "Login",
     "Email or Username",
     "Password",
     "Remember me",
     "Log In",
     "Google",
     "Facebook",
     "Github",
     "Don't have an account",
     "Create an account",
     "Register",
     "First Name",
     "Last Name",
     "Username",
     "signup",
     "Already have an account?",
     "Login here",
     "Enter captcha code",
     "Forbidden",
     "You don't have permission to access '/' on",
     "this server",
     "Back To Home",
     "404",
     "Page not",
     "found!",
     "Method Not",
     "Allowed",
     "419",
     "Sorry, your session",
     "has expired",
     "500",
     "Internal Server Error",
     "The server encountered an internal error misconfiguration and was unable to complete your request.",
     "Please contact the server administrator.",
     "You send",
     "You get",
     "Exchange now",
     "Please furnish the necessary address details for the transaction to proceed",
     "Trading pair",
     "Specify your preferred trading pair",
     "Wallet address",
     "Please enter the details for the cryptocurrency wallet address",
     "Complete the deposit for the exchange amount",
     "Trade",
     "Await the completion of your transaction",
     "Copyright",
     "All Rights Reserved",
     "Dashboard",
     "Support Ticket",
     "Payment Request",
     "Transaction",
     "Exchange",
     "Buy",
     "Sell",
     "Tracking",
     "Search",
     "Enter search keyword",
     "Result",
     "Account Settings",
     "2 FA Security",
     "Verification Center",
     "Sign Out",
     "Home",
     "Useful Links",
     "Support Links",
     "Contact Us",
     "Contact Information",
     "Phone:",
     "Email:",
     "Address:",
     "Drop Us a Line",
     "Your Name",
     "E-mail Address",
     "Your Subject",
     "Your Massage",
     "Send a massage",
     "Service fee",
     "Network fee",
     "Recipient address",
     "Exchange rate",
     "Please wait for a moment. is actively processing your trade. You can track the progress of your trade from this location.",
     "click here",
     "Transaction ID",
     "Payment Method",
     "Payment Currency",
     "Gateway Charge",
     "Minimum Limit",
     "Maximum Limit",
     "You Will Pay",
     "Please Make a Payment",
     "Time left to send",
     "Trade details",
     "Confirm & continue",
     "Processing",
     "Buy Crypto",
     "Destination wallet address",
     "Enter your",
     "recipient address",
     "I agree with Terms of Use and Privacy Policy",
     "Next step",
     "Overview",
     "With the fixed rate, you will receive the exact amount of crypto you see on this screen.",
     "Checkout",
     "Please provide the necessary account information to complete the trade",
     "Account details",
     "New Ticket",
     "Subject",
     "Message",
     "Upload New Photo",
     "reset",
     "Submit Ticket",
     "Tickets Log",
     "Status",
     "Last Reply",
     "Action",
     "Ticket# empty",
     "Ticket# Confirmation !",
     "Are you want to close ticket",
     "Close",
     "Confirm",
     "Crypto Buy Details",
     "Trade Information's",
     "Trx ID",
     "Exchange Rate",
     "Service Fees",
     "Network Fees",
     "Fiat Send Method",
     "Currency Information's",
     "Send Currency",
     "Receive Currency",
     "Send Amount",
     "Get Amount",
     "Receivable Amount",
     "Address Information's",
     "Destination address",
     "Rate",
     "Requested At",
     "All Send Currency",
     "All Get Currency",
     "All Status",
     "Awaiting Complete",
     "Trade Completed",
     "Trade Cancel",
     "Trade Refunded",
     "Filter",
     "Exchange Details",
     "Exchange Type",
     "Refund address",
     "Admin Receive address",
     "Crypto Sell Details",
     "Processing Fees",
     "Send address",
     "Refund Address",
     "Fiat Send Gateway",
     "Sell Crypto",
     "Remarks",
     "Amount",
     "Charge",
     "Created time",
     "2 Step Security",
     "Re-generate",
     "Two Factor Authenticator",
     "Copy",
     "Disable Two Factor Authenticator",
     "Enable Two Factor Authenticator",
     "Verify Your OTP",
     "Verify",
     "Re-generate Confirmation",
     "Are you want to Re-generate Authenticator ?",
     "Do not miss any single important notification! Allow your browser to get instant push notification",
     "Allow me",
     "Please allow your browser to get instant push notification. Allow it from notification setting.",
     "Exchange Crypto Statistics",
     "Pending Exchange",
     "last 30 days",
     "Complete Exchange",
     "Cancel Exchange",
     "Refund Exchange",
     "Buy Crypto Statistics",
     "Pending Buy",
     "Complete Buy",
     "Cancel Buy",
     "Refund Buy",
     "Sell Crypto Statistics",
     "Pending Sell",
     "Complete Sell",
     "Cancel Sell",
     "Refund Sell",
     "Exchange Crypto Figures",
     "Buy Crypto Figures",
     "Sell Crypto Figures",
     "Blog Details",
     "Recent Post",
     "Track your trade",
     "Enter your transaction id",
     "Track",
];

return $arr;
